language: node_js
node_js:
  - 10
  - 8

stages:
  - build
  - deploy

# keep the npm cache around to speed up installs
cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci
  - npm run build

before_script:
  - npm run lerna:prepublish

script:
  - npm run test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    script: npm run lerna:publish
    skip_cleanup: true
    on:
      node: 10
      tags: true
  - provider: script
    script: npm run lerna:publish -- --dist-tag next
    skip_cleanup: true
    on:
      node: 10
      branch: master
